[package]
name = "biscuit"
version = "0.1.0"
edition = "2021"
description = "A sleek, native multi-tab Markdown and LaTeX editor"
license = "MIT"
[dependencies]
gtk = { version = "0.8", package = "gtk4", features = ["v4_12"] }
libadwaita = { version = "0.6", features = ["v1_4"] }
sourceview5 = { version = "0.8" }
candle-core = "0.11.0"
candle-transformers = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
similar = "2.6"
directories = "5.0"
cairo-rs = "0.19"
glib = "0.19"
gdk = { version = "0.8", package = "gdk4" }
dirs = "7.0.0"
webkit6 = "0.3"
reqwest = { version = "0.12", features = ["blocking"] }
tokenizers = "0.23.2"


[build-dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
tar = "0.4"
flate2 = "1.0"
xz2 = "0.1"
zip = "0.6"
walkdir = "2.5.0"
serde_json = "1.0"

[package.metadata.deb]
maintainer = "GaganCJ <gaganjchandra2379@gmail.com>"
copyright = "2023, 7CGPA-Labs"
license-file = ["LICENSE", "4"]
depends = "$auto, libgtk-4-1, libadwaita-1-0, libwebkitgtk-6.0-4"
section = "editors"
priority = "optional"
extended-description = "A sleek, native multi-tab Markdown and LaTeX editor powered by GTK4 and Libadwaita. Maintained by 7CGPA-Labs."
assets = [
    ["target/release/biscuit", "usr/bin/", "755"],
]
